name: Python checks

on:
  push:
    branches:
      - main
      - performance-scale-2026-07-06
  pull_request:

jobs:
  syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Compile Python source
        run: python -m compileall -q .
